Ft ui ux rework 147181013
andela/vulcans-healthchecks pull request #2
Opened 2017-06-28 16:42 UTC by Alweezy

This alerts the user on the availability of a feature to collaboratively create and manage tasks.

2017-07-03 12:20 UTC, Alweezy commented
Follow [this link](https://mysterious-cliffs-81572.herokuapp.com/) to heroku deploy.

2017-07-05 15:10 UTC, NdagiStanley commented
@Alweezy let's fix the merge conflicts.

2017-07-10 15:06 UTC, Alweezy commented
@NdagiStanley conflicts resolved.

2017-07-10 17:10 UTC, NdagiStanley requested changes
Looks nice. I'll have a look at the deployment. In the meantime address the highlighted comments.
Feel free to push back.

2017-07-10 17:10 UTC, NdagiStanley commented on hc/wsgi.py
> +from whitenoise.django import DjangoWhiteNoise
Please note that line number `13` and `16` are the same.

2017-07-10 17:10 UTC, NdagiStanley commented on requirements.txt
> +rjsmin==1.0.12
Note that these are dependency libraries. Please confirm this.

2017-07-10 17:44 UTC, Alweezy commented on requirements.txt
> +rjsmin==1.0.12
That's true, let me solve that.

2017-07-10 18:09 UTC, Alweezy commented
Please check out, I have resolved the earlier communicated issues

2017-07-12 12:14 UTC, NdagiStanley commented on .gitignore
> +.idea
Good thing you added the `.idea` folder here.

2017-07-12 13:48 UTC, NdagiStanley approved these changes

2017-07-12 13:53 UTC, merged