#147181005 Create Blog on healthchecks
andela/vulcans-healthchecks pull request #5
Opened 2017-07-05 14:28 UTC by akash-011

#### What does this PR do?
Create a blog on the healthchecks website
#### Description of Task to be completed?
Blog posts can be viewed on the healthchecks website. Blog posts can be added from admin panel
#### How should this be manually tested?
App is live at [Heroku](https://healthblog.herokuapp.com/blog/ )
#### What are the relevant pivotal tracker stories?
Story ID : #147181005

2017-07-05 15:09 UTC, NdagiStanley commented
@akash-011 We'll need to resolve the conflicts.

2017-07-10 16:57 UTC, NdagiStanley commented
Way to go @akash-011

2017-07-10 17:05 UTC, NdagiStanley requested changes
I'll have a look at the deployment and maybe we can have a one-on-one if the need arises.

2017-07-10 17:05 UTC, NdagiStanley commented on hc/settings.py
> +
The comment is necessary, in my view. Maybe it just needed editing but not removing it.

2017-07-10 17:05 UTC, NdagiStanley commented on requirements.txt
> +rcssmin==1.0.6
This package is included but not used. Please confirm this.

2017-07-12 08:03 UTC, akash-011 commented on requirements.txt
> +rcssmin==1.0.6
Yes , I can confirm this

2017-07-12 12:15 UTC, NdagiStanley commented on hc/settings.py
> +SECRET_KEY = "----"
@akash-011 we need to revert this.

2017-07-13 12:24 UTC, NdagiStanley commented
@akash-011 You'll need to `git pull --rebase origin develop`

2017-07-17 14:03 UTC, NdagiStanley commented on hc/settings.py
> +SECRET_KEY = "----"
Please check check this.

2017-07-17 14:03 UTC, NdagiStanley commented on Procfile
> +web: gunicorn hc.wsgi --log-file -
Please revert this @akash-011 .

2017-07-17 16:58 UTC, NdagiStanley approved these changes

2017-07-18 09:39 UTC, merged